{
 "title": "Switch CISCO",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Grupo", "query": "*" },
   { "name": "Host", "query": "$Grupo.*" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Cisco IOS: ICMP ping" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Tempo Ligado",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Cisco IOS: Uptime (network)" },
     "itemTag": { "filter": "component: system" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "IP",
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "options": { "content": "**192.168.3.20**" },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch DELL PowerConnect 2848" },
     "item": { "filter": "ICMP: ICMP ping" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "#1: CPU utilization" },
     "itemTag": { "filter": "component: cpu" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Memory I/O",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "I/O: Memory utilization" },
     "itemTag": { "filter": "component: memory" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Memory Processador",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Processor: Memory utilization" },
     "itemTag": { "filter": "component: memory" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Firmware",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Cisco IOS: Operating system" },
     "itemTag": { "filter": "component: os" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Modelo do Switch",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Cisco IOS: System object ID" },
     "itemTag": { "filter": "component: system" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Memórias",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 2 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "I/O: Memory utilization" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Driver text: Memory utilization"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Processor: Memory utilization" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Memory Processador",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 2 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "I/O: Used memory" },
     "itemTag": { "filter": "component: memory" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Processor: Used memory" },
     "itemTag": { "filter": "component: memory" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Status PSU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Sw1, PS1 Normal, RPS NotExist: Power supply status"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Pacotes Loss",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Cisco IOS: ICMP loss" },
     "itemTag": { "filter": "component: network" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Status FAN",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Switch#1, Fan#1: Fan status" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Hardware serial number",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "1: Hardware serial number" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Status das interfaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Gi0/1",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/1(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/1" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/2",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/2(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/2" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/3",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/3(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/3" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/4",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/4(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/4" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/5",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/5(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/5" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/6",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/6(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/6" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/7",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/7(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/7" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/8",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/8(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/8" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/9",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/9(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/9" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/10",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/10(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/10" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/11",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/11(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/11" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/12",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/12(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/12" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/13",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/13(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/13" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/14",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/14(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/14" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/15",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/15(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/15" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/28",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/28(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/28" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/17",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/17(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/17" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/18",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/18(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/18" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/19",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/19(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/19" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/20",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/20(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/20" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/21",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/21(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/21" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/22",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/22(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/22" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/23",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/23(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/23" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/24",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/24(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/24" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/25",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/25(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/25" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/26",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/26(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/26" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/27",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/27(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/27" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/16",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/16(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/16" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/29",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/29(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/29" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/30",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/30(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/30" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/31",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/31(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/31" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/32",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/32(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/32" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/33",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/33(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/33" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/34",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/34(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/34" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/35",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/35(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/35" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/36",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/36(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/36" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/37",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/37(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/37" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/38",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/38(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/38" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/39",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/39(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/39" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/40",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/40(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/40" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/41",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/41(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/41" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/42",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/42(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/42" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/43",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/43(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/43" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/44",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/44(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/44" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/45",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/45(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/45" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/46",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/46(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/46" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/47",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/47(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/47" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Gi0/48",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/48(): Operational status"
     },
     "itemTag": { "filter": "interface: Gi0/48" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Informações de download x upload dos uplinks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Download",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/1(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/1" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/2(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/2" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/3(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/3" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/4(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/4" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/5(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/5" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/6(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/6" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/7(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/7" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/8(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/8" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/9(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/9" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/10(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/10" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/11(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/11" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/12(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/12" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/13(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/13" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Download",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/14(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/14" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/15(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/15" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/16(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/16" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/17(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/17" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/18(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/18" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/19(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/19" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/20(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/20" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/21(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/21" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/22(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/22" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/23(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/23" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Download",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/24(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/24" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/25(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/25" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/26(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/26" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/27(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/27" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/28(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/28" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/29(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/29" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/30(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/30" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/31(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/31" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/32(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/32" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/33(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/33" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Download",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/34(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/34" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/35(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/35" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/36(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/36" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/37(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/37" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/38(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/38" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/39(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/39" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/40(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/40" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/41(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/41" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/42(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/42" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/43(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/43" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": {
      "filter": "Interface Gi0/44(): Bits received"
     },
     "itemTag": { "filter": "interface: Gi0/44" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Upload",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/1(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/1" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/2(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/2" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/3(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/3" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/4(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/4" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/5(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/5" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/6(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/6" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/7(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/7" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/8(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/8" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/9(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/9" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/10(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/10" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/11(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/11" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/12(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/12" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/13(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/13" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Upload",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/14(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/14" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/15(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/15" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/16(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/16" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/17(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/17" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/18(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/18" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/19(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/19" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/20(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/20" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/21(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/21" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/22(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/22" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/23(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/23" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Upload",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/24(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/24" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/25(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/25" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/26(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/26" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/27(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/27" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/28(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/28" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/29(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/29" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/30(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/30" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/31(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/31" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/32(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/32" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/33(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/33" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Upload",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/34(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/34" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/35(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/35" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/36(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/36" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/37(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/37" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/38(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/38" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/39(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/39" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/40(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/40" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/41(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/41" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/42(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/42" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/43(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/43" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Interface Gi0/44(): Bits sent" },
     "itemTag": { "filter": "interface: Gi0/44" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "ICMP Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Time" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Cisco IOS: ICMP response time" },
     "itemTag": { "filter": "component: network" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "ICMP Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ping" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Cisco IOS: ICMP ping" },
     "itemTag": { "filter": "component: network" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "ICMP Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Loss" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "switch" },
     "host": { "filter": "Switch Cisco Catalyst 2960G" },
     "item": { "filter": "Cisco IOS: ICMP loss" },
     "itemTag": { "filter": "component: network" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  }
 ]
}